/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bandit.view;

/**
 *
 * @author Christian
 */
public class View extends javax.swing.JFrame
{

  /**
   * @return the jLabel1
   */
  public javax.swing.JLabel getjLabel1()
  {
    return jLabel1;
  }

  /**
   * @return the lblText1
   */
  public javax.swing.JLabel getLblText1()
  {
    return lblText1;
  }

  /**
   * @return the lblText2
   */
  public javax.swing.JLabel getLblText2()
  {
    return lblText2;
  }

  /**
   * @return the lblText3
   */
  public javax.swing.JLabel getLblText3()
  {
    return lblText3;
  }

  /**
   * @return the btnStart
   */
  public javax.swing.JButton getBtnStart()
  {
    return btnStart;
  }

  /**
   * @return the btnStop
   */
  public javax.swing.JButton getBtnStop()
  {
    return btnStop;
  }

  /**
   * @return the lblText
   */
  public javax.swing.JLabel getLblText()
  {
    return lblText1;
  }

  /**
   * Creates new form View
   */
  public View()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    Buttons = new javax.swing.JPanel();
    btnStart = new javax.swing.JButton();
    btnStop = new javax.swing.JButton();
    Numbers = new javax.swing.JPanel();
    lblText1 = new javax.swing.JLabel();
    lblText2 = new javax.swing.JLabel();
    lblText3 = new javax.swing.JLabel();

    jLabel1.setText("jLabel1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Bandit");

    btnStart.setText("Start");
    Buttons.add(btnStart);

    btnStop.setText("Stop");
    Buttons.add(btnStop);

    getContentPane().add(Buttons, java.awt.BorderLayout.SOUTH);

    lblText1.setFont(new java.awt.Font("Dialog", 0, 120)); // NOI18N
    lblText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblText1.setText("1");
    lblText1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    Numbers.add(lblText1);

    lblText2.setFont(new java.awt.Font("Dialog", 0, 120)); // NOI18N
    lblText2.setText("2");
    lblText2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    Numbers.add(lblText2);

    lblText3.setFont(new java.awt.Font("Dialog", 0, 120)); // NOI18N
    lblText3.setText("3");
    lblText3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    Numbers.add(lblText3);

    getContentPane().add(Numbers, java.awt.BorderLayout.CENTER);

    setSize(new java.awt.Dimension(416, 239));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new View().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Buttons;
  private javax.swing.JPanel Numbers;
  private javax.swing.JButton btnStart;
  private javax.swing.JButton btnStop;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel lblText1;
  private javax.swing.JLabel lblText2;
  private javax.swing.JLabel lblText3;
  // End of variables declaration//GEN-END:variables
}
